# Uncomment the next line to define a global platform for your project
platform :ios, '15.2'


target 'Simon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Simon
  pod 'Firebase/Core'
  pod 'Firebase/Database'

end
